sudo: false
language: node_js
node_js:
  - '0.12.1'
addons:
  code_climate:
    repo_token: d8a6coneZxjp6bhbUxsJ
after_script:
  - codeclimate < lcov.info
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install compass'
