sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'

before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
addons:
  code_climate:
    repo_token: d8a6coneZxjp6bhbUxsJ
after_script:
  - codeclimate < lcov.info
